version: '3.4'

services:
  worker:
    build:
      context: ./GoMailWorker
      dockerfile: ./Dockerfile
    networks:
      - net
    depends_on:
      - mysql
      - redis
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  nginx:
    volumes:
      - ./MailWorkerApi:/var/www/html/MailWorkerApi
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    image: nginx:1.19-alpine
    networks:
      - net
    ports:
      - 80:80
    depends_on:
      - app
    links:
      - app
  app:
    build:
      context: ./MailWorkerApi
      dockerfile: ./Dockerfile
    networks:
      - net
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    restart: unless-stopped
    volumes:
      - ./MailWorkerApi:/var/www/html/MailWorkerApi
  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - net
    environment:
      MYSQL_ROOT_PASSWORD: linuxlinux
      MYSQL_DATABASE: mailWorker
      MYSQL_USER: rajko
      MYSQL_PASSWORD: linuxlinux
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    networks:
      - net
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  mysql:

networks:
  net:
    driver: bridge
