version: "3.4"

networks: 
  net: 
    driver: bridge
services: 
  app:
    build: 
      context: ./MailWorkerApi
      dockerfile: .
    networks: 
      - net
    depends_on:
      - db
      - redis
      - nginx
    links: 
      - db
      - redis
    restart: unless-stopped
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks: 
      - net
    environment: 
      MYSQL_ROOT_PASSWORD: linuxlinux
      MYSQL_DATABASE: mailWorker
      MYSQL_USER: rajko
      MYSQL_PASSWORD: linuxlinux
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 6603:3306
  redis:
    image: redis
    networks: 
      - net
    ports: 
      - 6379:6379 
    restart: unless-stopped
  nginx:
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    image: nginx:1.19-alpine
    networks: 
      - net
    depends_on: 
      - redis
      - db
    ports:
      - 80:80